export const SITE = {
  website: "https://manassalian.dev/",
  author: "Manas S",
  profile: "https://manassalian.dev/",
  desc: "Manas S — cybersecurity, programming, and everything in between.",
  title: "Manas S",
  logo: "",
  ogImage: "astropaper-og.jpg",
  lightAndDarkMode: false,
  postPerIndex: 4,
  postPerPage: 4,
  scheduledPostMargin: 15 * 60 * 1000,
  showArchives: true,
  showBackButton: false,
  editPost: {
    enabled: false,
    text: "",
    url: "",
  },
  dynamicOgImage: false,
  dir: "ltr",
  lang: "en",
  timezone: "Asia/Kolkata",
} as const;
